- hosts: tst-vsu-tst-001
  become: true
  gather_facts: no
  tasks:
  - name: Ansible grep pattern with ignore_errors example
    shell: iptables -L -nv | grep -i accept
    #egister: grep_output
    #ignore_errors: true

  #- debug:
   # var: grep_output.stdout_lines
    #when: grep_output.stdout != "
