---
- hosts: 172.16.199.5
  gather_facts: false
  connection: local

  tasks:
   - name: show run 
     ios_command:
       commands:
         - show run   
     register: config

   - name: save output to /etc/ansible/backup
   - local_action: "copy content='{{ config.stdout }}' dest=/etc/ansible/backup/config.txt"
     #copy: 
       #content: "{{ config.stdout[0] }}"
       #dest: '/etc/ansible/backup/show_run_{{ inventory_hostname }}.txt'
