---
- hosts: 172.16.199.5
  gather_facts: true
  connection: local
 
  tasks:
   - name: show run 
     ios_command:
       commands:
   - show run 
     host: "{{ ansible_host }}"
     username: camd0505
     password: n@omi00c
     register: config
 
   - name: save output to /data/ansible/backup_switches
     copy: 
     content: "{{ config.stdout[0] }}"
     dest: "/data/ansible/backup_switches/show_run_{{ inventory_hostname }}.txt"
