# Rebooting DMZ Linux Servers
---
- hosts: dmz
  gather_facts: true
  become: true

  tasks:
    - name: Restarting DMZ servers
      shell: sleep 10 && /sbin/shutdown -r now 
      async: 300
      poll: 0
      become: true
      
    - name: waiting 30 secs for server to come back
      local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=120
      become: false

