---
- hosts: vsu-mon-001
  become: true
  gather_facts: no
  tasks:
  - name: checking if the file exists
    stat: path=/etc/cron.weekly
    register: perform_OpenSCAP_analysis.bash
  
  - name: Move file to Home
    command: mv /etc/cron.weekly/perform_OpenSCAP_analysis.bash /home/camd0505
          
