---
- hosts: beheer
  become: true
  gather_facts: no
  tasks:
  - name: checking if the file exists
    stat: 
      path=/etc/cron.weekly/perform_OpenSCAP_analysis.bash
    register: openscap
  
  - name: Move file
    command: mv /etc/cron.weekly/perform_OpenSCAP_analysis.bash /usr/local/src/
    when: openscap.stat.exists
          
