---
- hosts: beheer
  become: true
  gather_facts: no
  tasks:
  - name: stat perform_OpenSCAP_analysis.bash
    stat: path=/etc/cron.weekly
    register: stat perform_OpenSCAP_analysis.bash
    
  - name: Move perform_OpenSCAP_analysis.bash to Home
    command: mv /etc/cron.weekly/perform_OpenSCAP_analysis.bash /home/camd0505
      
