---
- hosts: beheer
  become: true
  gather_facts: no
  tasks:
  - name: Move /etc/cron.weekly to Home
    command: mv /etc/cron.weekly/perform_OpenSCAP_analysis.bash /home/root/
    changed_when: false
    
