- hosts: toa,prod,beheer,dmz
  become: yes
  become_method: sudo
  gather_facts: no
  any_errors_fatal: true
  tasks:

  - name: Server needs a reboot?
    command: /bin/needs-restarting -r
    changed_when: false
