- hosts: toa,beheer,prod,dmz
  become: true
  gather_facts: no
  tasks:
  - name: Set Password
    shell: id -u deij0908
    register: user_exists
    ignore_errors: true
  
  - name: Change Password
    user:
      name: deij0908
      password: $1$3Zdze7Vx$ZvgfYy/fCKwOpa6TA1/0s0
      update_password: always
