# Rebooting Production Linux Servers
---
- hosts: dmz-vsu-atm-001,dmz-vsu-atm-002,dmz-vsu-apl-003,vsu-web-001,vsu-web-003
  gather_facts: true
  become: true

  tasks:
    - name: Restarting Production servers
      shell: sleep 10 && /sbin/shutdown -r now 
      async: 300
      poll: 0
      become: true
      
    - name: waiting 30 secs for server to come back
      local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=60
      become: false
