# Rebooting Linux Servers
---
# hosts: prod
- hosts: vsu-apl-001,vsu-web-002
  gather_facts: no

  tasks:
    - name: reboot host
      shell: sleep 10 && /sbin/shutdown -r now 
      async: 300
      poll: 0
      become: true

    - name: waiting for server booting up
      local_action: wait_for
      args:
        host: '*'
        port: 22
        delay: 30
        timeout: 120
        state: started
      become: false
