---
- hosts: tst-vsu-tst-001
  become: true
  gather_facts: no
  tasks:
  - name: find files older than 180 days
    find:
      path: /tmp
      age: 500d
      recurse: yes
      file_type: file
    register: oldfiles
  - name: Remove files
    file:
      path: '{{ /data/HOSTS }}'
      state: absent
    with_items:
      - '{{ oldfiles.files }}'
