---
# Playbook that configures Nagios clients (either update or new install) of Nagios Cross Platform Agent (NCPA)
- hosts: toa,prod,beheer
  become: true



  roles:
    - nagiosrepo
    - ncpa_rhel

  tasks:
  - name: restart ncpa
    service:
      name: ncpa_listener
      state: restarted
