---
- hosts: toa,beheer,prod,dmz
  gather_facts: no
  become: true
  tasks:
  
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - httpd
    - mariadb
